services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: calculatorGCC_nginx_prod
    depends_on:
      - backend
      - phpmyadmin
    labels:
      - "traefik.http.services.nginx.loadbalancer.server.port=3000"
    environment:
      NODE_PROJET: production
      ENABLE_SSL: ${ENABLE_SSL:-false}
    ports:
      - "3000:3000"
    # plus besoin de volumes frontend_build
    volumes:
      - ssl_certs:/etc/nginx/ssl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - calculatorGCC_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: calculatorGCC_backend_prod
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 7000
      HOSTNAME: ${HOSTNAME:-localhost}
      ENABLE_SSL: ${ENABLE_SSL:-false}
      DATABASE_URL: mysql://${DB_USER:-calculatorgcc_user}:${DB_PASSWORD}@mariadb:3306/${DB_NAME:-calculatorgcc}
    env_file:
      - ./backend/srcs/.env
    restart: unless-stopped
    networks:
      - calculatorGCC_network

  mariadb:
    image: mariadb:latest
    container_name: calculatorGCC_mariadb_prod
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-calculatorgcc}
      MYSQL_USER: ${DB_USER:-calculatorgcc_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /data/calculatorgcc/mariadb:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - calculatorGCC_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: calculatorGCC_phpmyadmin_prod
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 50M
      PMA_ABSOLUTE_URI: https://${HOSTNAME:-localhost}/phpmyadmin/
    restart: unless-stopped
    networks:
      - calculatorGCC_network

networks:
  calculatorGCC_network:
    driver: bridge

volumes:
  ssl_certs:
